controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

default_admin:
    path: '/admin'
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'admin_dashboard_index'